name: Build python

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: node:25.8.1
    steps:
      - name: Create python3-pip
        run: |
          apt-get update
          apt-get -y install python3-pip
          npm config set prefix /usr/local
          npm install -g serverless@3.39.0
          npm install serverless-python-requirements
          npm install --save-dev serverless-ignore
          npm i -D serverless-dotenv-plugin
